In [6]:
import pandas as pd
import numpy as np

np.random.seed(0)

stock_data = pd.read_csv("train.csv")
reqired_columns = stock_data.loc[:,['date','close','open','high','low','volume']]

print(reqired_columns)

              date      close        open        high         low      volume
0       2012-06-22  95.610001  122.656593   24.797176  162.793195         NaN
1       2013-02-27  27.410000   48.429243   84.148858   62.911473  24383100.0
2       2010-07-19  25.230000  144.410310  162.714072    7.813419  38181800.0
3       2015-12-31  30.000000  -12.281054 -128.017977  -38.679447    944600.0
4       2012-11-12  68.480003  -48.492927  204.768157   -6.981525   2780300.0
...            ...        ...         ...         ...         ...         ...
283080  2013-02-15  87.440070  112.351785  -25.211752   53.999501   2296800.0
283081  2010-03-01  40.580002   36.940292   46.563556  -34.540507   3896000.0
283082  2016-12-29  63.900002  -96.360628   33.326362  198.863154   1098700.0
283083  2012-09-18  44.369999  121.623729   45.178067   80.536696   1241900.0
283084  2013-03-14  61.470001  -30.025808   11.959084  171.348424    683800.0

[283085 rows x 6 columns]

In [11]:
reqired_columns.to_csv('cleaning_data.csv', index=False)

In [12]:
reqired_columns.head()

         date      close        open        high         low      volume
0  2012-06-22  95.610001  122.656593   24.797176  162.793195         NaN
1  2013-02-27  27.410000   48.429243   84.148858   62.911473  24383100.0
2  2010-07-19  25.230000  144.410310  162.714072    7.813419  38181800.0
3  2015-12-31  30.000000  -12.281054 -128.017977  -38.679447    944600.0
4  2012-11-12  68.480003  -48.492927  204.768157   -6.981525   2780300.0

In [13]:
cleaning_data = pd.read_csv('cleaning_data.csv')

cleaning_data.head(25)

          date       close        open        high         low      volume
0   2012-06-22   95.610001  122.656593   24.797176  162.793195         NaN
1   2013-02-27   27.410000   48.429243   84.148858   62.911473  24383100.0
2   2010-07-19   25.230000  144.410310  162.714072    7.813419  38181800.0
3   2015-12-31   30.000000  -12.281054 -128.017977  -38.679447    944600.0
4   2012-11-12   68.480003  -48.492927  204.768157   -6.981525   2780300.0
5   2010-04-27   43.209999  133.900205   58.260369  -94.695877   2423300.0
6   2015-06-30   64.430000   81.805889  166.617148  132.990850   1332400.0
7   2010-08-31   39.849998  100.580188    3.585313  -39.114110    780200.0
8   2010-06-10    7.075000   62.642614  -10.967004 -125.707260   2300000.0
9   2014-05-16   72.010002  -60.374316   47.230339  -31.348079   1308600.0
10  2015-06-29   66.720001   49.582645  -13.906795  -29.982533   9706700.0
11  2011-01-21   29.190001   89.741932   46.758260  237.079512  11322100.0
12  2013-03-05   24.650000  -29.710433   84.413174  -91.922022   2528000.0
13  2011-11-30   35.810001   64.924646  -46.958305   42.180971   1346200.0
14  2013-01-18    6.746632  110.719498   47.204372   49.573629   9881000.0
15  2016-05-17   34.299999 -136.370936    8.360086   38.801257   1722300.0
16  2011-11-28   66.797698    5.536540  214.521388  317.475009   2111600.0
17  2010-11-09  100.919998   37.162916   96.818802   24.739178   1446200.0
18  2011-10-20   29.790001 -103.443825   25.727044    1.172132   3562500.0
19           0   42.610001         NaN   71.962428  -34.298840   5878000.0
20  2016-10-06  234.720001  393.538743  237.260509  390.539598   1899700.0
21  2012-01-17   77.779999  129.251550  263.811697  126.916340    819400.0
22  2013-07-12         NaN   59.179687   18.964647 -110.744400   3726500.0
23  2014-01-27   68.699997   86.661462  127.872698 -112.771622    959500.0
24  2011-12-21   35.430000   42.811908   99.668673   21.156909   1094900.0

In [14]:
missing_values_count = cleaning_data.isnull().sum(0)

missing_values_count[0:23]

C:\Users\kaush\AppData\Local\Temp\ipykernel_1136\3377331042.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  missing_values_count = cleaning_data.isnull().sum(0)

date      1558
close     1510
open      1440
high      1540
low       1466
volume    1490
dtype: int64

In [15]:
total_cells = np.prod(cleaning_data.shape)
missing_cells = missing_values_count.sum(0)

percentage_missing = (missing_cells/total_cells)*100
print(percentage_missing)

0.5301116861248978

C:\Users\kaush\AppData\Local\Temp\ipykernel_1136\3702712939.py:2: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  missing_cells = missing_values_count.sum(0)

In [16]:
import datetime

In [17]:
cleaning_data['date'].dtype

cleaning_data.head()

         date      close        open        high         low      volume
0  2012-06-22  95.610001  122.656593   24.797176  162.793195         NaN
1  2013-02-27  27.410000   48.429243   84.148858   62.911473  24383100.0
2  2010-07-19  25.230000  144.410310  162.714072    7.813419  38181800.0
3  2015-12-31  30.000000  -12.281054 -128.017977  -38.679447    944600.0
4  2012-11-12  68.480003  -48.492927  204.768157   -6.981525   2780300.0

In [18]:
import pandas as pd

cleaning_data = pd.read_csv('cleaning_data.csv')

dates = pd.to_datetime(
    cleaning_data['date'],
    format='mixed',
    errors='coerce'
)

# Display rows with invalid dates
print(cleaning_data[dates.isna()])

       date       close         open        high          low      volume
19        0   42.610001          NaN   71.962428   -34.298840   5878000.0
42      NaN   72.760002     0.000000   49.937417   148.574983   7207600.0
160       0   10.620000          NaN  -29.794725  -133.440417  29085000.0
166       0   40.029999   150.571850  -15.786293  -105.884814   2608400.0
208     NaN   40.000000    76.698421   81.513795    82.214400    565500.0
...     ...         ...          ...         ...          ...         ...
279913  NaN   74.379997    96.837411   61.576492   138.069447   1201800.0
280651    0   17.965000          NaN   39.280593   187.876111  10256000.0
280841    0         NaN   -43.227938  -22.662922    97.426069   1162900.0
280899  NaN   39.990002    40.349336  122.279087    91.410056   1734900.0
282605  NaN  680.039978  1066.874558  692.214344  1019.600199         0.0

[3107 rows x 6 columns]

In [19]:
cleaning_data =cleaning_data.sort_values(by='date')

print(cleaning_data)

       date       close         open        high          low      volume
52882     0   47.259998    25.090467  136.042890     6.413531   1572600.0
134848    0   58.599998          NaN   58.081423     8.932308   1373800.0
224255    0   67.900002     0.000000  130.435078          NaN   3550200.0
26208     0         NaN   557.784306  483.513956   651.896392    156400.0
54678     0   47.330002    53.231158   -6.372201   -84.613042   2539000.0
...     ...         ...          ...         ...          ...         ...
275057  NaN   24.613733    34.050316 -162.323187   -69.041725  11638200.0
275729  NaN   31.900000     3.986395  -55.012712  -139.551623   1749300.0
279913  NaN   74.379997    96.837411   61.576492   138.069447   1201800.0
280899  NaN   39.990002    40.349336  122.279087    91.410056   1734900.0
282605  NaN  680.039978  1066.874558  692.214344  1019.600199         0.0

[283085 rows x 6 columns]

In [20]:
import numpy as np

cleaning_data['date'] = cleaning_data['date'].replace(['0', 0], np.nan)

In [21]:
new_cleaning_data = cleaning_data.dropna(subset=['date'])
print(new_cleaning_data)

              date      close        open        high         low      volume
272725  2010-01-04  17.100000  -42.674833  130.446834  -75.176610  16587400.0
49941   2010-01-04  16.969999   -5.833224  -45.913540   28.366938  13573400.0
156678  2010-01-04  61.630001   93.127349  -99.408874    1.364021    954400.0
193368  2010-01-04  53.639999   17.465291   38.251749  -26.618489   2469700.0
42426   2010-01-04  11.180000  -48.558995   20.493241   71.187448   9625000.0
...            ...        ...         ...         ...         ...         ...
141181  2016-12-30  98.260002   62.349554  101.976747  148.765964   1299600.0
260651  2016-12-30  78.029999   63.719385   79.534081  178.043330    432300.0
78235   2016-12-30  22.990000   14.154027   92.355422 -114.323854   1514800.0
146314  2016-12-30  36.270000   65.963717   11.617766   -5.911086   3452600.0
117420  2016-12-30  65.199997  122.837839  101.747017  139.708688   5909500.0

[279978 rows x 6 columns]

In [22]:
new_cleaning_data.to_csv('cleaning_data.csv', index=False)

In [23]:
updated_csv = pd.read_csv('cleaning_data.csv')
print(updated_csv.head(30))

          date      close        open        high         low      volume
0   2010-01-04  17.100000  -42.674833  130.446834  -75.176610  16587400.0
1   2010-01-04  16.969999   -5.833224  -45.913540   28.366938  13573400.0
2   2010-01-04  61.630001   93.127349  -99.408874    1.364021    954400.0
3   2010-01-04  53.639999   17.465291   38.251749  -26.618489   2469700.0
4   2010-01-04  11.180000  -48.558995   20.493241   71.187448   9625000.0
5   2010-01-04  48.570000  -80.111598   65.043627    0.601845   2728100.0
6   2010-01-04  22.970000  -66.028408   45.540712 -117.333467   2457200.0
7   2010-01-04  30.809999  -47.444739    7.300034  -69.303889   2353000.0
8   2010-01-04  37.979105   79.026772   73.606605    5.694866   8727000.0
9   2010-01-04  31.469999   38.598739  -19.949474   12.568996   3472500.0
10  2010-01-04  26.100000  -34.225315   -6.745471 -102.234824    876900.0
11  2010-01-04  45.380001   27.125633   46.922709         NaN   2142300.0
12  2010-01-04  53.509998  -15.029824  148.142095 -129.871778   4890300.0
13  2010-01-04  21.240000   -0.135357   -3.544391 -121.090134   2460200.0
14  2010-01-04  14.610000    4.126267   51.765171  -95.774731   7552600.0
15  2010-01-04   6.094303 -135.464958   -3.233636  104.960799   6905600.0
16  2010-01-04  18.150000  -24.232405    9.718533  145.650721   3850500.0
17  2010-01-04  19.270000   22.979443  -12.549190  -27.695208   1650400.0
18  2010-01-04  10.240000  -79.582441  -64.281354  -55.151900  12718800.0
19  2010-01-04  19.940001  107.338021  -75.076012    3.251419   3110300.0
20  2010-01-04  29.850000 -114.811426   18.252421 -115.810017    390000.0
21  2010-01-04  27.760000  -59.157590   -7.519522  122.618741   1299300.0
22  2010-01-04  60.020000         NaN  192.533968   60.242229    782400.0
23  2010-01-04  27.270000   20.489497  188.422524  162.494009   1859700.0
24  2010-01-04  10.058923  110.275718   98.914019  111.570421  22511600.0
25  2010-01-04  28.290001   54.532514   52.773658   30.599363   6127700.0
26  2010-01-04  30.950001  -36.622873   93.632851   66.335695  38409100.0
27  2010-01-04  30.940001   62.024489   65.649773   45.426239   2887600.0
28  2010-01-04  30.299999   84.132195   40.330588 -182.141310   2413400.0
29  2010-01-04  24.125000  109.344759   86.175649 -129.462701   1128200.0

In [24]:
missing_values_count = updated_csv.isnull().sum(0)

missing_values_count[0:23]

C:\Users\kaush\AppData\Local\Temp\ipykernel_1136\2564698893.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  missing_values_count = updated_csv.isnull().sum(0)

date         0
close     1387
open      1323
high      1396
low       1344
volume    1394
dtype: int64

In [25]:
cleaning_data = updated_csv.dropna(subset=['close','open','high','low','volume'])
missing_values_count = cleaning_data.isnull().sum(0)

missing_values_count[0:23]

C:\Users\kaush\AppData\Local\Temp\ipykernel_1136\61566007.py:2: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  missing_values_count = cleaning_data.isnull().sum(0)

date      0
close     0
open      0
high      0
low       0
volume    0
dtype: int64

In [26]:
cleaning_data.to_csv('train_data.csv', index=False)