In [6]:
import pandas as pd
import numpy as np

In [7]:
stock_data = pd.read_csv("train.csv")

np.random.seed(0)

In [15]:
stock_data.head()

,date,high,low,momentum_index,beta_indicator,risk_premium,index,volatility_factor,technical_score,oscillator_value,liquidity_ratio,open,quant_index,trend_strength,market_sentiment,close,volume,alpha_signal,symbols
0,2012-06-22,24.797176,162.793195,153.349972,90.290064,277.383362,62235.0,105.868473,128.280484,38.359969,154.844720,122.656593,3817.034814,-48.017571,-42.552169,95.610001,NaN,126.405476,MRO
1,2013-02-27,84.148858,62.911473,123.066280,99.689780,116.635811,48784.0,116.700703,8.730951,-35.866296,-53.482145,48.429243,4522.962303,149.657066,221.824044,27.410000,24383100.0,-22.111984,HRS
2,2010-07-19,162.714072,7.813419,50.140068,-30.373609,145.254746,233118.0,302.752221,-40.118103,-50.358825,27.921367,144.410310,1277.720791,284.891018,58.834733,25.230000,38181800.0,20.068656,Low
3,2015-12-31,-128.017977,-38.679447,-21.881272,-173.386894,-123.314003,28867.0,-3.662459,81.801806,-53.396998,-11.014860,-12.281054,636.545321,-210.812924,137.518347,30.000000,944600.0,75.297134,ULTA
4,2012-11-12,204.768157,-6.981525,-38.978256,64.867265,-90.095079,182732.0,-157.223822,-76.111066,149.650023,-29.829836,-48.492927,3044.960784,293.534187,15.030557,68.480003,2780300.0,82.056444,Low

In [9]:
reqired_columns = stock_data.loc[:,['date','close']]

print(reqired_columns)

              date      close
0       2012-06-22  95.610001
1       2013-02-27  27.410000
2       2010-07-19  25.230000
3       2015-12-31  30.000000
4       2012-11-12  68.480003
...            ...        ...
283080  2013-02-15  87.440070
283081  2010-03-01  40.580002
283082  2016-12-29  63.900002
283083  2012-09-18  44.369999
283084  2013-03-14  61.470001

[283085 rows x 2 columns]

In [16]:
reqired_columns.to_csv('cleaning_data.csv', index=False)

In [18]:
cleaning_data = pd.read_csv('cleaning_data.csv')

cleaning_data.head(25)

          date       close
0   2012-06-22   95.610001
1   2013-02-27   27.410000
2   2010-07-19   25.230000
3   2015-12-31   30.000000
4   2012-11-12   68.480003
5   2010-04-27   43.209999
6   2015-06-30   64.430000
7   2010-08-31   39.849998
8   2010-06-10    7.075000
9   2014-05-16   72.010002
10  2015-06-29   66.720001
11  2011-01-21   29.190001
12  2013-03-05   24.650000
13  2011-11-30   35.810001
14  2013-01-18    6.746632
15  2016-05-17   34.299999
16  2011-11-28   66.797698
17  2010-11-09  100.919998
18  2011-10-20   29.790001
19           0   42.610001
20  2016-10-06  234.720001
21  2012-01-17   77.779999
22  2013-07-12         NaN
23  2014-01-27   68.699997
24  2011-12-21   35.430000

In [ ]:
missing_values_count = cleaning_data.isnull().sum(0)

missing_values_count[0:23]

C:\Users\kaush\AppData\Local\Temp\ipykernel_13452\3377331042.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  missing_values_count = cleaning_data.isnull().sum(0)

date     1558
close    1510
dtype: int64

In [22]:
total_cells = np.prod(cleaning_data.shape)
missing_cells = missing_values_count.sum(0)

percentage_missing = (missing_cells/total_cells)*100
print(percentage_missing)

0.5418867124715191

C:\Users\kaush\AppData\Local\Temp\ipykernel_13452\3702712939.py:2: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  missing_cells = missing_values_count.sum(0)

In [29]:
import datetime

In [34]:
cleaning_data['date'].dtype

cleaning_data.head()

         date      close
0  2012-06-22  95.610001
1  2013-02-27  27.410000
2  2010-07-19  25.230000
3  2015-12-31  30.000000
4  2012-11-12  68.480003

In [42]:
import pandas as pd

cleaning_data = pd.read_csv('cleaning_data.csv')

dates = pd.to_datetime(
    cleaning_data['date'],
    format='mixed',
    errors='coerce'
)

# Display rows with invalid dates
print(cleaning_data[dates.isna()])

       date       close
19        0   42.610001
42      NaN   72.760002
160       0   10.620000
166       0   40.029999
208     NaN   40.000000
...     ...         ...
279913  NaN   74.379997
280651    0   17.965000
280841    0         NaN
280899  NaN   39.990002
282605  NaN  680.039978

[3107 rows x 2 columns]

In [51]:
cleaning_data =cleaning_data.sort_values(by='date')

print(cleaning_data)

              date       close
52882            0   47.259998
140071           0   20.010000
16144            0   79.610001
31471            0         NaN
134848           0   58.599998
...            ...         ...
152874  2016-12-30   74.440002
274825  2016-12-30  102.779999
260651  2016-12-30   78.029999
112131  2016-12-30   44.340000
117420  2016-12-30   65.199997

[281527 rows x 2 columns]

In [57]:
import numpy as np

cleaning_data['date'] = cleaning_data['date'].replace(['0', 0], np.nan)

In [58]:
new_cleaning_data = cleaning_data.dropna(subset=['date'])
print(new_cleaning_data)

              date       close
263523  2010-01-04   30.299999
231918  2010-01-04    6.546667
61263   2010-01-04   48.570000
156678  2010-01-04   61.630001
193368  2010-01-04   53.639999
...            ...         ...
152874  2016-12-30   74.440002
274825  2016-12-30  102.779999
260651  2016-12-30   78.029999
112131  2016-12-30   44.340000
117420  2016-12-30   65.199997

[279978 rows x 2 columns]

In [59]:
new_cleaning_data.to_csv('cleaning_data.csv', index=False)

In [61]:
updated_csv = pd.read_csv('cleaning_data.csv')
print(updated_csv.head(30))

          date      close
0   2010-01-04  30.299999
1   2010-01-04   6.546667
2   2010-01-04  48.570000
3   2010-01-04  61.630001
4   2010-01-04  53.639999
5   2010-01-04  11.180000
6   2010-01-04  30.809999
7   2010-01-04  26.100000
8   2010-01-04  45.380001
9   2010-01-04  53.509998
10  2010-01-04  17.100000
11  2010-01-04  16.969999
12  2010-01-04  25.459999
13  2010-01-04  37.979105
14  2010-01-04  31.469999
15  2010-01-04  14.610000
16  2010-01-04  40.349998
17  2010-01-04  41.980000
18  2010-01-04  42.860001
19  2010-01-04  10.058923
20  2010-01-04  18.150000
21  2010-01-04  27.760000
22  2010-01-04  28.290001
23  2010-01-04  30.950001
24  2010-01-04   6.094303
25  2010-01-04  22.970000
26  2010-01-04  21.240000
27  2010-01-04  30.940001
28  2010-01-04  16.750000
29  2010-01-04  19.940001

In [62]:
missing_values_count = updated_csv.isnull().sum(0)

missing_values_count[0:23]

C:\Users\kaush\AppData\Local\Temp\ipykernel_13452\2564698893.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  missing_values_count = updated_csv.isnull().sum(0)

date        0
close    1387
dtype: int64

In [65]:
cleaning_data = updated_csv.dropna(subset=['close'])
missing_values_count = cleaning_data.isnull().sum(0)

missing_values_count[0:23]

C:\Users\kaush\AppData\Local\Temp\ipykernel_13452\3875363181.py:2: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  missing_values_count = cleaning_data.isnull().sum(0)

date     0
close    0
dtype: int64

In [66]:
cleaning_data.to_csv('train_data.csv', index=False)