In [2]:
import pandas as pd
import numpy as np

np.random.seed(0)

stock_data = pd.read_csv("test.csv")
reqired_columns = stock_data.loc[:,['date','close','open','high','low','volume']]

print(reqired_columns)

              date       close        open        high         low     volume
0       2015-02-17   42.099998  -11.284320  106.520498    9.341813  9040600.0
1       2012-09-20  102.639999  172.322151   -1.941571  119.482832  1356100.0
2       2011-05-04   46.150002    5.420504   20.636255   29.394771  6866500.0
3       2013-03-20   51.862000   74.334335  -20.326080   61.258867  4552000.0
4       2011-06-24   40.790001   24.079310   71.009360   63.233695  1387100.0
...            ...         ...         ...         ...         ...        ...
177058  2016-06-06   72.739998   30.382494  -22.748656   34.127972   749400.0
177059  2012-02-23   27.990000   83.027346  -50.862863  -19.859546  7850500.0
177060  2015-01-12  103.160004   67.651814  142.844740   94.151090  1869200.0
177061  2010-02-19   17.253334  -87.508953   35.174488   42.694600   743800.0
177062  2013-06-24   19.990000   44.160821   43.182700    9.888618  1858200.0

[177063 rows x 6 columns]

In [19]:
reqired_columns.to_csv('test_data.csv', index=False)

In [20]:
reqired_columns.head()

         date       close        open        high         low     volume
0  2015-02-17   42.099998  -11.284320  106.520498    9.341813  9040600.0
1  2012-09-20  102.639999  172.322151   -1.941571  119.482832  1356100.0
2  2011-05-04   46.150002    5.420504   20.636255   29.394771  6866500.0
3  2013-03-20   51.862000   74.334335  -20.326080   61.258867  4552000.0
4  2011-06-24   40.790001   24.079310   71.009360   63.233695  1387100.0

In [21]:
test_data = pd.read_csv('test_data.csv')

test_data.head(25)

          date       close        open        high         low      volume
0   2015-02-17   42.099998  -11.284320  106.520498    9.341813   9040600.0
1   2012-09-20  102.639999  172.322151   -1.941571  119.482832   1356100.0
2   2011-05-04   46.150002    5.420504   20.636255   29.394771   6866500.0
3   2013-03-20   51.862000   74.334335  -20.326080   61.258867   4552000.0
4   2011-06-24   40.790001   24.079310   71.009360   63.233695   1387100.0
5   2016-06-28   25.350000  -27.296152   33.622967   14.654831    814000.0
6   2014-05-21   22.580000  -61.561512    2.128863   95.998897   2090900.0
7   2015-04-02   52.180000  136.407926   60.076234  -18.895484   2381300.0
8   2012-07-09   43.126079  -65.760661  -24.880335   79.271921   2179000.0
9   2015-07-20  104.220001  214.280938  190.383612  126.822285   2123900.0
10  2016-01-06  553.239990  720.828366  677.219001  618.786272    503700.0
11  2015-05-04   43.279999   62.808642   20.941704  164.812338   3982400.0
12  2014-10-27   84.839996  160.929658   84.746023   17.453194   3602500.0
13  2016-02-26   42.549999   97.048733   12.015567   50.385033   3829800.0
14  2010-09-10   17.969999  -58.542380   55.944863  -13.498164  68814700.0
15  2011-08-23   58.770000  135.958668   38.428885   48.729453   1345000.0
16  2016-04-08   78.760002  146.891236   59.940809   88.465347    982400.0
17  2014-04-07   52.759998   94.948441   37.336929   13.502973   1995800.0
18  2014-06-03   99.889999  282.447764  147.831918   64.318068   2224700.0
19  2013-01-04  151.100006  104.976874  212.760349  165.428836    509800.0
20  2015-10-22   13.200000  122.445805  -25.665501   49.295704  14450000.0
21  2016-08-11    9.900000  -70.189866  -19.899333  -23.087996   4448400.0
22  2011-05-26   40.309132   20.111922   55.552104   90.796571   2985600.0
23  2016-12-30   40.500000  164.132693   24.543056   90.957169   3267900.0
24  2014-09-05   49.939999  121.387870   52.548582   69.916847  11920900.0

In [26]:
missing_values_count = test_data.isnull().sum(0)

missing_values_count[0:23]

C:\Users\kaush\AppData\Local\Temp\ipykernel_28492\3236918914.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  missing_values_count = test_data.isnull().sum(0)

date      285
close     290
open      277
high      258
low       279
volume    258
dtype: int64

In [27]:
total_cells = np.prod(test_data.shape)
missing_cells = missing_values_count.sum(0)

percentage_missing = (missing_cells/total_cells)*100
print(percentage_missing)

0.15502956574778468

C:\Users\kaush\AppData\Local\Temp\ipykernel_28492\1641938995.py:2: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  missing_cells = missing_values_count.sum(0)

In [28]:
import datetime

In [29]:
test_data['date'].dtype

test_data.head()

         date       close        open        high         low     volume
0  2015-02-17   42.099998  -11.284320  106.520498    9.341813  9040600.0
1  2012-09-20  102.639999  172.322151   -1.941571  119.482832  1356100.0
2  2011-05-04   46.150002    5.420504   20.636255   29.394771  6866500.0
3  2013-03-20   51.862000   74.334335  -20.326080   61.258867  4552000.0
4  2011-06-24   40.790001   24.079310   71.009360   63.233695  1387100.0

In [30]:
import pandas as pd

test_data = pd.read_csv('test_data.csv')

dates = pd.to_datetime(
    test_data['date'],
    format='mixed',
    errors='coerce'
)


print(test_data[dates.isna()])

       date      close        open        high         low      volume
125       0  13.220000  -25.883929   53.546381  -10.726366  17252800.0
272       0  34.049999  -44.860240  -19.227027         NaN   1693200.0
968     NaN  31.290001  -76.873693   29.728121   -3.961201  10254200.0
1842    NaN  64.650002  166.074923   91.865499  135.075316   1162100.0
2257    NaN   0.000000  110.357387   71.709713   18.966217   1871300.0
...     ...        ...         ...         ...         ...         ...
175898  NaN  37.810001   15.870127    3.908169  -44.322428   1837000.0
176143    0  29.010000   17.328993   47.409621   -5.467281   3473000.0
176263  NaN        NaN   65.168373   58.582870   36.786551   6200800.0
176813    0   0.000000  -86.509771  -25.551481         NaN   4380500.0
176874    0        NaN  705.988933  667.794158  573.046314    351000.0

[572 rows x 6 columns]

In [31]:
test_data=test_data.sort_values(by='date')

print(test_data)

       date       close        open        high         low      volume
44898     0   30.629999  -26.243686   69.008839   35.615569   3881300.0
101701    0   13.150000   10.450773   46.905916  -27.078996         0.0
137920    0   37.959999  -66.120578    3.751095  113.598369   1456200.0
73426     0  110.699997  117.472366  202.028159   75.616156   2149900.0
43866     0   32.236251  -42.386850  -47.001805   16.759885   8247300.0
...     ...         ...         ...         ...         ...         ...
173971  NaN   68.919998  -25.424550  123.114326   78.402798    962400.0
175371  NaN   36.340000  103.881090   10.726078   -2.751689  24563800.0
175604  NaN  107.220001  147.882027  124.471820  105.768649   4429600.0
175898  NaN   37.810001   15.870127    3.908169  -44.322428   1837000.0
176263  NaN         NaN   65.168373   58.582870   36.786551   6200800.0

[177063 rows x 6 columns]

In [32]:
import numpy as np

test_data['date'] = test_data['date'].replace(['0', 0], np.nan)

In [33]:
new_test_data = test_data.dropna(subset=['date'])
print(new_test_data)

              date       close        open        high         low      volume
94743   2010-01-04   37.603162  -13.618553   22.367132  -35.244308   3930100.0
90146   2010-01-04   54.520000  204.138203  -32.729727   88.526625    961000.0
52380   2010-01-04   22.879999    3.533557   16.203385   42.169703  12891700.0
71595   2010-01-04   29.615000   51.527634   -3.974742   34.473905   1908400.0
137971  2010-01-04   19.780001  -46.254132  -67.653237   21.292147  14023600.0
...            ...         ...         ...         ...         ...         ...
42286   2016-12-30  104.370003   39.641770  198.640199  125.341218    926400.0
52568   2016-12-30  268.739990  323.764543  252.716597  324.535164    581200.0
164479  2016-12-30  115.559998  125.953786  190.742516  105.169657    698000.0
33839   2016-12-30   38.060001   55.834175   94.134773   55.985282   2221100.0
172870  2016-12-30   54.090000   92.719450  137.025570   11.192784   4638300.0

[176491 rows x 6 columns]

In [34]:
new_test_data.to_csv('test_data.csv', index=False)

In [35]:
updated_csv = pd.read_csv('test_data.csv')
print(updated_csv.head(30))

          date      close        open        high         low       volume
0   2010-01-04  37.603162  -13.618553   22.367132  -35.244308    3930100.0
1   2010-01-04  54.520000  204.138203  -32.729727   88.526625     961000.0
2   2010-01-04  22.879999    3.533557   16.203385   42.169703   12891700.0
3   2010-01-04  29.615000   51.527634   -3.974742   34.473905    1908400.0
4   2010-01-04  19.780001  -46.254132  -67.653237   21.292147   14023600.0
5   2010-01-04  22.650000   72.108229  -55.622680   43.002906    2176100.0
6   2010-01-04  28.080000  -29.227219   24.604520  111.991877    4284000.0
7   2010-01-04  42.009998   -6.441256    0.287339   89.462426     286000.0
8   2010-01-04  19.952722  -52.905606   84.060925    1.856596    1759600.0
9   2010-01-04  48.310001   78.226831   74.462326   98.969246     497000.0
10  2010-01-04  25.370001  -43.804842   -2.208206  -18.193094    1169700.0
11  2010-01-04  33.869999   54.399471  -23.335987   23.130030    1574200.0
12  2010-01-04  38.090000  -36.590665    0.320525   57.235827     712900.0
13  2010-01-04  14.300000   47.795238   15.350539  -11.458792   18615100.0
14  2010-01-04  15.690000    7.309615   10.951396  -74.661185  180845200.0
15  2010-01-04  67.010002  130.824334  138.440414   49.873132     721000.0
16  2010-01-04  19.990000  -67.406538   29.808862   59.343037    2975900.0
17  2010-01-04  35.153528   15.283500   72.044224  -14.702430    1502200.0
18  2010-01-04  13.660000    8.476797   84.340302   77.011823    6263800.0
19  2010-01-04  47.790001   17.502102  -18.205442  -11.215715    4923600.0
20  2010-01-04  50.830002   64.290397   44.697953   35.152529    3473200.0
21  2010-01-04  35.080002   12.490202   -2.680193   34.878710    1062400.0
22  2010-01-04  29.180000  -20.022298  -50.766070   35.815223    1518700.0
23  2010-01-04  63.959999  -27.968251   70.756019   22.788547    4741400.0
24  2010-01-04  10.672500  135.958978  -16.062790  -57.212314   15743600.0
25  2010-01-04  10.280000  -47.274647   -6.178650    5.222019   60855800.0
26  2010-01-04  74.242704   57.461836   70.441243   42.209657    3450400.0
27  2010-01-04  10.280000  -47.274647   -6.178650    5.222019   60855800.0
28  2010-01-04  49.349998  -55.923491   23.809628   67.156384    7844500.0
29  2010-01-04  33.000000   44.337946  -69.401277   64.224790    5671300.0

In [37]:
missing_values_count = updated_csv.isnull().sum(0)

missing_values_count[0:23]

C:\Users\kaush\AppData\Local\Temp\ipykernel_28492\2564698893.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  missing_values_count = updated_csv.isnull().sum(0)

date        0
close     271
open      265
high      240
low       261
volume    239
dtype: int64

In [38]:
test_data = updated_csv.dropna(subset=['close','open','high','low','volume'])
missing_values_count = test_data.isnull().sum(0)

missing_values_count[0:23]

C:\Users\kaush\AppData\Local\Temp\ipykernel_28492\1337936236.py:2: Pandas4Warning: Starting with pandas version 4.0 all arguments of sum will be keyword-only.
  missing_values_count = test_data.isnull().sum(0)

date      0
close     0
open      0
high      0
low       0
volume    0
dtype: int64

In [ ]:
cleaning_data.to_csv('test_data.csv', index=False)

: